version: "3.8"

services:
  predict-core:
    image: nguyenhkbui/5001-stock-predict-core
    container_name: 5001-predict-core
    ports:
      - "5001:5001"
    volumes:
      - shared-models:/tmp/models

  api-gateway:
    image: nguyenhkbui/5002-stock-api-gateway
    container_name: 5002-stock-api-gateway
    ports:
      - "5002:5002"
    volumes:
      - shared-models:/tmp/models
    depends_on:
      - predict-core

volumes:
  shared-models:
